replicaCount: 2

image:
  repository: harbor.bitworm.net/reservai-prod/app
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: harbor-creds

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: reservai.net
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: bytealigned.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  port: 8080

app:
  dbHost: "postgres-postgresql.prod.svc.cluster.local"
  dbName: "reservai"

secrets:
  dbCredentials: "db-credentials"
  jwtSecret: "jwt-secret"
  verifyTokenSecret: "verify-token-secret"
  passwordResetSecret: "password-reset-secret"
  oAuthCredentials: "oauth-credentials"