apiVersion: batch/v1
kind: Job
metadata:
  name: reservai-migration
  labels:
    app: reservai
    role: migration
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["alembic", "upgrade", "head"]
        env:
        - name: DB_HOST
          value: {{ .Values.app.dbHost }}
        - name: DB_NAME
          value: {{ .Values.app.dbName }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.dbCredentials }}
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.dbCredentials }}
              key: password
